jaffle_shop:
  target: dev
  outputs:
    dev:
      type: sqlserver
      driver: 'ODBC Driver 18 for SQL Server' # (The ODBC Driver installed on your system)
      server: 10.44.16.21
      port: 1433
      database: KPI
      schema: dbo
      user: pacbi 
      password: As1234567